// ── Shared subgroup field registry ────────────────────────────────────────────
// Single source of truth for all subgroup technical attribute fields.
// Used by: Add/Edit Line forms (TechnicalAttrsSection) and Technical Datasheets.
// Order and labels here drive the display in both places.

export type SubgroupField = {
  key: string;
  label: string;
  type?: "text" | "number" | "select";
  opts?: string[];
  colSpan?: boolean;
  cascade?: { targetKey: string; map: Record<string, string> };
};

// ── Shared field sets ─────────────────────────────────────────────────────────
const MOTOR_FIELDS: SubgroupField[] = [
  { key: "motor_type",          label: "Motor Type",          type: "select", opts: ["Induction","Synchronous","BLDC"] },
  { key: "power",               label: "Power (kW)",          type: "number" },
  { key: "voltage",             label: "Voltage",             type: "select", opts: ["415 V","690 V","3300 V","6600 V","11000 V"] },
  { key: "speed",               label: "Speed (RPM)",         type: "number" },
  { key: "frequency",           label: "Frequency (Hz)",      type: "select", opts: ["50 Hz","60 Hz"] },
  { key: "duty",                label: "Duty",                type: "select", opts: ["S1 (Continuous)","S2","S3","S4"] },
  { key: "mounting",            label: "Mounting",            type: "select", opts: ["Horizontal (B3)","Flange Mounted (B5)","Vertical (V1)"] },
  { key: "ip_rating",           label: "IP Rating",           type: "select", opts: ["IP44","IP55","IP65","IP66"] },
  { key: "efficiency_class",    label: "Efficiency Class",    type: "select", opts: ["IE2","IE3","IE4"] },
  { key: "cooling_type",        label: "Cooling Type",        type: "select", opts: ["TEFC","TEAAC","Open","Forced Ventilation"] },
  { key: "material",            label: "Frame Material",      type: "select", opts: ["Cast Iron","Aluminium","Fabricated Steel"] },
  { key: "area_classification", label: "Area Classification", type: "select", opts: ["Zone 0","Zone 1","Zone 2","Safe Area"] },
  { key: "explosion_protection",label: "Explosion Protection",type: "select", opts: ["Flameproof Ex d","Intrinsically Safe Ex i","Non-Flameproof"] },
  { key: "gas_group",           label: "Gas Group",           type: "select", opts: ["IIA","IIB","IIC"] },
  { key: "temperature_class",   label: "Temperature Class",   type: "select", opts: ["T1","T2","T3","T4","T5","T6"] },
  { key: "vfd_compatible",      label: "VFD Compatible",      type: "select", opts: ["Yes","No"] },
  { key: "make", label: "Make", type: "text", colSpan: true },
];

const PRESSURE_INSTR_FIELDS: SubgroupField[] = [
  { key: "instrument_type",     label: "Instrument Type",      type: "select", opts: ["Pressure Transmitter (PT)","Pressure Switch (PS)","Pressure Gauge (PG)","Pressure Indicator (PI)","Differential Pressure Transmitter (DPT)"] },
  { key: "measurement_type",    label: "Measurement Type",     type: "select", opts: ["Gauge Pressure","Absolute Pressure","Differential Pressure"] },
  { key: "range_min",           label: "Range Min",            type: "text" },
  { key: "range_max",           label: "Range Max",            type: "text" },
  { key: "range_unit",          label: "Range Unit",           type: "select", opts: ["bar","mbar","kPa","MPa","psi","mmHg","inH2O"] },
  { key: "process_fluid",       label: "Process Fluid",        type: "text" },
  { key: "wetted_material",     label: "Wetted Material",      type: "select", opts: ["SS316","SS304","Hastelloy","Titanium","PTFE lined"] },
  { key: "connection_size",     label: "Connection Size",      type: "select", opts: ['1/4"','1/2"','3/4"','1"','1.5"','2"'] },
  { key: "connection_type",     label: "Connection Type",      type: "select", opts: ["BSP","NPT","Flanged","Tri-clamp"] },
  { key: "output_signal",       label: "Output Signal",        type: "select", opts: ["4–20 mA","0–10 V","HART","Profibus","Modbus","NO/NC Contact","Digital"] },
  { key: "enclosure_type",      label: "Enclosure",            type: "select", opts: ["IP65","IP66","IP67","Weatherproof","Flameproof"] },
  { key: "operating_temp",      label: "Process Temp",         type: "text" },
  { key: "area_classification", label: "Area Classification",  type: "select", opts: ["Zone 0","Zone 1","Zone 2","Safe Area"] },
  { key: "explosion_protection",label: "Explosion Protection", type: "select", opts: ["Flameproof Ex d","Intrinsically Safe Ex i","Non-Flameproof","Ex e","Ex n"] },
  { key: "certification",       label: "Certification",        type: "select", opts: ["ATEX","IECEx","PESO","NA"] },
  { key: "gas_group",           label: "Gas Group",            type: "select", opts: ["IIA","IIB","IIC"] },
  { key: "temperature_class",   label: "Temperature Class",    type: "select", opts: ["T1","T2","T3","T4","T5","T6"] },
];

const ISOLATION_FIELDS: SubgroupField[] = [
  { key: "valve_type",            label: "Valve Type",            type: "select", opts: ["Ball Valve","Gate Valve","Globe Valve","Butterfly Valve","Check Valve","Needle Valve","Plug Valve"] },
  { key: "size_nb",               label: "Size (NB)",             type: "select", opts: ["15","20","25","32","40","50","65","80","100","150","200","250","300"] },
  { key: "pressure_rating",       label: "Pressure Rating",       type: "select", opts: ["Class 150","Class 300","Class 600","Class 900","Class 1500","PN10","PN16","PN25","PN40"] },
  { key: "end_connection",        label: "End Connection",        type: "select", opts: ["Flanged","Screwed","Socket Weld","Butt Weld","Wafer","Lug"] },
  { key: "body_material",         label: "Body Material",         type: "select", opts: ["CI","CS","SS304","SS316","Duplex","WCB","LCB"] },
  { key: "ball_design",           label: "Ball Design",           type: "text" },
  { key: "bore_type",             label: "Bore Type",             type: "text" },
  { key: "ball_material",         label: "Ball Material",         type: "text" },
  { key: "trim_material",         label: "Trim Material",         type: "select", opts: ["SS304","SS316","Stellite","Hard Facing","13% Cr"] },
  { key: "seat_material",         label: "Seat Material",         type: "text" },
  { key: "seat_type",             label: "Seat Type",             type: "select", opts: ["Soft Seat (PTFE)","Metal Seat","Soft Seat (NBR)"] },
  { key: "stem_packing",          label: "Stem Packing",          type: "text" },
  { key: "locking_device",        label: "Locking Device",        type: "text" },
  { key: "disc_material",         label: "Disc Material",         type: "text" },
  { key: "disc_mounting",         label: "Disc Mounting",         type: "text" },
  { key: "wedge_type",            label: "Wedge Type",            type: "text" },
  { key: "stem_type",             label: "Stem Type",             type: "text" },
  { key: "bonnet_type",           label: "Bonnet Type",           type: "text" },
  { key: "operation_type",        label: "Operation Type",        type: "select", opts: ["Manual","Pneumatic (DA)","Pneumatic (SA)","Electric Actuator","Hand Wheel"] },
  { key: "design_pressure",       label: "Design Pressure (bar)", type: "text" },
  { key: "operating_pressure",    label: "Oper. Pressure (bar)",  type: "text" },
  { key: "design_temperature",    label: "Design Temp (°C)",      type: "text" },
  { key: "operating_temperature", label: "Oper. Temp (°C)",       type: "text" },
  { key: "process_fluid",         label: "Process Fluid",         type: "text" },
  { key: "area_classification",   label: "Area Classification",   type: "select", opts: ["Zone 0","Zone 1","Zone 2","Safe Area"] },
  { key: "make", label: "Make", type: "text", colSpan: true },
];

// ── Main registry ─────────────────────────────────────────────────────────────
export const SUBGROUP_TA_FIELDS: Record<string, SubgroupField[]> = {

  // ── PUMPS ──────────────────────────────────────────────────────────────────
  centrifugal: [
    { key: "pump_type",           label: "Pump Type",           type: "select", opts: ["End Suction","Split Case","Multistage","Vertical Inline","Vertical Turbine"] },
    { key: "mounting",            label: "Mounting",            type: "select", opts: ["Base Mounted","Inline","Vertical"] },
    { key: "drive_type",          label: "Drive Type",          type: "select", opts: ["Motor Driven","Engine Driven"] },
    { key: "service_type",        label: "Service Type",        type: "select", opts: ["Continuous","Intermittent","Standby"] },
    { key: "seal_type",           label: "Seal Type",           type: "select", opts: ["Single Mechanical Seal","Double Mechanical Seal","Gland Packing"] },
    { key: "material_class",      label: "Material Class",      type: "select", opts: ["CI","CS","SS304","SS316","Duplex"] },
    { key: "impeller_type",       label: "Impeller Type",       type: "text" },
    { key: "casing_material",     label: "Casing Material",     type: "text" },
    { key: "shaft_material",      label: "Shaft Material",      type: "text" },
    { key: "flow_rate",           label: "Flow Rate",           type: "text" },
    { key: "head",                label: "Head",                type: "text" },
    { key: "operating_temp",      label: "Operating Temp",      type: "text" },
    { key: "fluid",               label: "Fluid",               type: "text" },
    { key: "suction_size",        label: "Suction Size",        type: "text" },
    { key: "discharge_size",      label: "Discharge Size",      type: "text" },
    { key: "motor_power",         label: "Motor Power",         type: "text" },
    { key: "coupling_type",       label: "Coupling Type",       type: "text" },
    { key: "area_classification", label: "Area Classification", type: "text" },
    { key: "design_standard",     label: "Design Standard",     type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  gear: [
    { key: "gear_type",      label: "Gear Type",       type: "select", opts: ["External Gear","Internal Gear"] },
    { key: "mounting",       label: "Mounting",        type: "select", opts: ["Base Mounted","Skid Mounted","Vertical"] },
    { key: "drive_type",     label: "Drive Type",      type: "select", opts: ["Motor Driven","Engine Driven"] },
    { key: "service_type",   label: "Service Type",    type: "select", opts: ["Continuous","Intermittent","Standby"] },
    { key: "seal_type",      label: "Seal Type",       type: "select", opts: ["Mechanical Seal","Gland Packing","Magnetic Drive"] },
    { key: "material_class", label: "Material Class",  type: "select", opts: ["CI","CS","SS304","SS316"] },
    { key: "flow_rate",      label: "Flow Rate",       type: "text" },
    { key: "pressure",       label: "Discharge Pressure", type: "text" },
    { key: "fluid",          label: "Fluid",           type: "text" },
    { key: "operating_temp", label: "Operating Temp",  type: "text" },
    { key: "area_classification", label: "Area Classification", type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  screw: [
    { key: "screw_type",     label: "Screw Type",      type: "text" },
    { key: "num_screws",     label: "Number of Screws",type: "text" },
    { key: "service_type",   label: "Service Type",    type: "text" },
    { key: "seal_type",      label: "Seal Type",       type: "text" },
    { key: "material_class", label: "Material Class",  type: "text" },
    { key: "flow_rate",      label: "Flow Rate",       type: "text" },
    { key: "pressure",       label: "Pressure",        type: "text" },
    { key: "fluid",          label: "Fluid",           type: "text" },
    { key: "operating_temp", label: "Operating Temp",  type: "text" },
    { key: "area_classification", label: "Area Classification", type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  vacuum_boosters: [
    { key: "vacuum_type",        label: "Vacuum Type",        type: "text" },
    { key: "capacity",           label: "Capacity",           type: "text" },
    { key: "suction_pressure",   label: "Suction Pressure",   type: "text" },
    { key: "discharge_pressure", label: "Discharge Pressure", type: "text" },
    { key: "fluid",              label: "Process Gas",        type: "text" },
    { key: "material_class",     label: "Material Class",     type: "text" },
    { key: "operating_temp",     label: "Operating Temp",     type: "text" },
    { key: "seal_type",          label: "Seal Type",          type: "text" },
    { key: "area_classification",label: "Area Classification",type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  vacuum_pump: [
    { key: "vacuum_type",        label: "Vacuum Type",        type: "text" },
    { key: "capacity",           label: "Capacity",           type: "text" },
    { key: "suction_pressure",   label: "Suction Pressure",   type: "text" },
    { key: "discharge_pressure", label: "Discharge Pressure", type: "text" },
    { key: "fluid",              label: "Process Gas",        type: "text" },
    { key: "material_class",     label: "Material Class",     type: "text" },
    { key: "operating_temp",     label: "Operating Temp",     type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  multistage: [
    { key: "multistage_type",     label: "Multistage Type",    type: "text" },
    { key: "lineshaft_type",      label: "Lineshaft Type",     type: "text" },
    { key: "num_stages",          label: "Number of Stages",   type: "number" },
    { key: "flow_rate",           label: "Flow Rate",          type: "text" },
    { key: "head",                label: "Head",               type: "text" },
    { key: "fluid",               label: "Fluid",              type: "text" },
    { key: "material_class",      label: "Material Class",     type: "text" },
    { key: "operating_temp",      label: "Operating Temp",     type: "text" },
    { key: "seal_type",           label: "Seal Type",          type: "text" },
    { key: "area_classification", label: "Area Classification",type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  dosing_metering: [
    { key: "pump_type",      label: "Pump Type",      type: "text" },
    { key: "actuator_type",  label: "Actuator Type",  type: "text" },
    { key: "flow_rate",      label: "Flow Rate",      type: "text" },
    { key: "pressure",       label: "Discharge Pressure", type: "text" },
    { key: "fluid",          label: "Fluid",          type: "text" },
    { key: "material_class", label: "Material Class", type: "text" },
    { key: "seal_type",      label: "Seal Type",      type: "text" },
    { key: "area_classification", label: "Area Classification", type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  pump_skid: [
    { key: "description",         label: "Description",        type: "text", colSpan: true },
    { key: "fluid",               label: "Fluid",              type: "text" },
    { key: "capacity",            label: "Capacity",           type: "text" },
    { key: "configuration",       label: "Configuration",      type: "text" },
    { key: "area_classification", label: "Area Classification",type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],

  // ── MOTORS ──────────────────────────────────────────────────────────────────
  non_flameproof: MOTOR_FIELDS,
  flameproof:     MOTOR_FIELDS,
  motors:         MOTOR_FIELDS,

  // ── INSTRUMENTS ─────────────────────────────────────────────────────────────
  pressure: PRESSURE_INSTR_FIELDS,
  temperature: [
    { key: "instrument_type",     label: "Instrument Type",      type: "select", opts: ["Thermocouple (TC)","RTD","Temperature Transmitter (TT)","Temperature Switch (TS)","Temperature Indicator (TI)"] },
    { key: "sensor_type",         label: "Sensor Type",          type: "select", opts: ["Type K","Type J","Type T","Type E","PT100","PT1000"] },
    { key: "range_min",           label: "Range Min",            type: "text" },
    { key: "range_max",           label: "Range Max",            type: "text" },
    { key: "range_unit",          label: "Range Unit",           type: "select", opts: ["°C","°F","K"] },
    { key: "thermowell",          label: "Thermowell",           type: "text" },
    { key: "insertion_length",    label: "Insertion Length",     type: "text" },
    { key: "wetted_material",     label: "Wetted Material",      type: "select", opts: ["SS316","SS304","Inconel","Hastelloy"] },
    { key: "connection_size",     label: "Connection Size",      type: "select", opts: ['1/4"','1/2"','3/4"','1"'] },
    { key: "connection_type",     label: "Connection Type",      type: "select", opts: ["BSP","NPT","Flanged"] },
    { key: "output_signal",       label: "Output Signal",        type: "select", opts: ["4–20 mA","0–10 V","HART","Resistance (RTD)","Thermocouple mV"] },
    { key: "enclosure",           label: "Enclosure",            type: "select", opts: ["IP65","IP66","Weatherproof","Flameproof"] },
    { key: "area_classification", label: "Area Classification",  type: "select", opts: ["Zone 0","Zone 1","Zone 2","Safe Area"] },
    { key: "explosion_protection",label: "Explosion Protection", type: "select", opts: ["Ex d (Flameproof)","Ex i (Intrinsically Safe)","Non-Flameproof","Ex e"] },
    { key: "certification",       label: "Certification",        type: "select", opts: ["ATEX","IECEx","PESO","NA"] },
    { key: "gas_group",           label: "Gas Group",            type: "select", opts: ["IIA","IIB","IIC"] },
    { key: "temperature_class",   label: "Temperature Class",    type: "select", opts: ["T1","T2","T3","T4","T5","T6"] },
  ],
  flow: [
    { key: "instrument_type",     label: "Instrument Type",      type: "select", opts: ["Flow Transmitter (FT)","Flow Switch (FS)","Flow Indicator (FI)","Rotameter","Orifice Plate","Vortex Flow Meter","Electromagnetic Flow Meter"] },
    { key: "measurement_type",    label: "Measurement Type",     type: "select", opts: ["Volumetric Flow","Mass Flow","Velocity"] },
    { key: "range_min",           label: "Range Min",            type: "text" },
    { key: "range_max",           label: "Range Max",            type: "text" },
    { key: "range_unit",          label: "Range Unit",           type: "select", opts: ["m³/hr","L/hr","L/min","kg/hr"] },
    { key: "process_fluid",       label: "Process Fluid",        type: "text" },
    { key: "line_size",           label: "Line Size (NB)",       type: "text" },
    { key: "connection_type",     label: "Connection Type",      type: "select", opts: ["Flanged","Wafer","Insertion","Inline"] },
    { key: "output_signal",       label: "Output Signal",        type: "select", opts: ["4–20 mA","Pulse","HART","Profibus","Modbus"] },
    { key: "area_classification", label: "Area Classification",  type: "select", opts: ["Zone 0","Zone 1","Zone 2","Safe Area"] },
    { key: "explosion_protection",label: "Explosion Protection", type: "select", opts: ["Flameproof Ex d","Intrinsically Safe Ex i","Non-Flameproof"] },
    { key: "certification",       label: "Certification",        type: "text" },
    { key: "gas_group",           label: "Gas Group",            type: "text" },
  ],
  level: [
    { key: "instrument_type",     label: "Instrument Type",      type: "select", opts: ["Level Transmitter (LT)","Level Switch (LS)","Level Gauge (LG)","Guided Wave Radar (GWR)","Ultrasonic","Float","Displacer"] },
    { key: "measurement_type",    label: "Measurement Type",     type: "select", opts: ["Continuous","Point Level","Interface"] },
    { key: "range_min",           label: "Range Min",            type: "text" },
    { key: "range_max",           label: "Range Max",            type: "text" },
    { key: "range_unit",          label: "Range Unit",           type: "select", opts: ["mm","m","inch","cm","%"] },
    { key: "process_fluid",       label: "Process Fluid",        type: "text" },
    { key: "connection_size",     label: "Connection Size (NB)", type: "text" },
    { key: "connection_type",     label: "Connection Type",      type: "select", opts: ["Flanged","NPT","BSP","Tri-clamp"] },
    { key: "output_signal",       label: "Output Signal",        type: "select", opts: ["4–20 mA","HART","Relay","Profibus","Modbus"] },
    { key: "area_classification", label: "Area Classification",  type: "select", opts: ["Zone 0","Zone 1","Zone 2","Safe Area"] },
    { key: "explosion_protection",label: "Explosion Protection", type: "select", opts: ["Flameproof Ex d","Intrinsically Safe Ex i","Non-Flameproof"] },
    { key: "certification",       label: "Certification",        type: "text" },
  ],

  // ── VALVES ──────────────────────────────────────────────────────────────────
  isolation: ISOLATION_FIELDS,
  control: [
    { key: "valve_type",            label: "Valve Type",            type: "text" },
    { key: "size_nb",               label: "Size (NB)",             type: "text" },
    { key: "pressure_rating",       label: "Pressure Rating",       type: "text" },
    { key: "end_connection",        label: "End Connection",        type: "text" },
    { key: "body_material",         label: "Body Material",         type: "text" },
    { key: "actuator_type",         label: "Actuator Type",         type: "select", opts: ["Pneumatic Diaphragm","Pneumatic Piston","Electric Actuator","Hydraulic Actuator"] },
    { key: "fail_action",           label: "Fail Action",           type: "select", opts: ["Fail Open (FO)","Fail Close (FC)","Fail Last (FL)"] },
    { key: "input_signal",          label: "Input Signal",          type: "select", opts: ["4–20 mA","4–20 mA + HART","Foundation Fieldbus","PROFIBUS PA","Modbus RTU"] },
    { key: "positioner",            label: "Positioner",            type: "select", opts: ["With Positioner","Without Positioner"] },
    { key: "trim_style",            label: "Trim Style",            type: "text" },
    { key: "flow_characteristic",   label: "Flow Characteristic",   type: "text" },
    { key: "trim_material",         label: "Trim Material",         type: "text" },
    { key: "seat_material",         label: "Seat Material",         type: "text" },
    { key: "leakage_class",         label: "Leakage Class",         type: "text" },
    { key: "bonnet_type",           label: "Bonnet Type",           type: "text" },
    { key: "packing_material",      label: "Packing Material",      type: "text" },
    { key: "handwheel",             label: "Handwheel",             type: "select", opts: ["Yes","No"] },
    { key: "bypass_valve",          label: "Bypass Valve",          type: "select", opts: ["Yes","No"] },
    { key: "design_pressure",       label: "Design Pressure (bar)", type: "text" },
    { key: "operating_pressure",    label: "Oper. Pressure (bar)",  type: "text" },
    { key: "design_temperature",    label: "Design Temp (°C)",      type: "text" },
    { key: "operating_temperature", label: "Oper. Temp (°C)",       type: "text" },
    { key: "process_fluid",         label: "Process Fluid",         type: "text" },
    { key: "area_classification",   label: "Area Classification",   type: "text" },
    { key: "certification",         label: "Certification",         type: "text" },
    { key: "explosion_protection",  label: "Explosion Protection",  type: "text" },
    { key: "gas_group",             label: "Gas Group",             type: "text" },
    { key: "temperature_class",     label: "Temperature Class",     type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  on_off: [
    { key: "valve_type",            label: "Valve Type",            type: "text" },
    { key: "size_nb",               label: "Size (NB)",             type: "text" },
    { key: "pressure_rating",       label: "Pressure Rating",       type: "text" },
    { key: "end_connection",        label: "End Connection",        type: "text" },
    { key: "body_material",         label: "Body Material",         type: "text" },
    { key: "actuation_type",        label: "Actuation Type",        type: "text" },
    { key: "fail_action",           label: "Fail Action",           type: "select", opts: ["Fail Open (FO)","Fail Close (FC)","Fail Last (FL)"] },
    { key: "service_type",          label: "Service Type",          type: "text" },
    { key: "seat_material",         label: "Seat Material",         type: "text" },
    { key: "bore_type",             label: "Bore Type",             type: "text" },
    { key: "stem_seal",             label: "Stem Seal",             type: "text" },
    { key: "fire_safe",             label: "Fire Safe",             type: "select", opts: ["Yes","No"] },
    { key: "anti_static_device",    label: "Anti-static Device",    type: "select", opts: ["Yes","No"] },
    { key: "design_pressure",       label: "Design Pressure (bar)", type: "text" },
    { key: "operating_pressure",    label: "Oper. Pressure (bar)",  type: "text" },
    { key: "design_temperature",    label: "Design Temp (°C)",      type: "text" },
    { key: "operating_temperature", label: "Oper. Temp (°C)",       type: "text" },
    { key: "process_fluid",         label: "Process Fluid",         type: "text" },
    { key: "area_classification",   label: "Area Classification",   type: "text" },
    { key: "certification",         label: "Certification",         type: "text" },
    { key: "explosion_protection",  label: "Explosion Protection",  type: "text" },
    { key: "valve_standard",        label: "Valve Standard",        type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  safety: [
    { key: "valve_type",          label: "Valve Type",           type: "select", opts: ["Safety Relief Valve (SRV)","Pressure Safety Valve (PSV)","Rupture Disc","Breather Valve (Conservation Vent)","Vacuum Breaker"] },
    { key: "inlet_size",          label: "Inlet Size (NB)",      type: "text" },
    { key: "outlet_size",         label: "Outlet Size (NB)",     type: "text" },
    { key: "size_nb",             label: "Size (NB)",            type: "text" },
    { key: "set_pressure",        label: "Set Pressure (bar)",   type: "text" },
    { key: "back_pressure",       label: "Back Pressure (bar)",  type: "text" },
    { key: "pressure_rating",     label: "Pressure Rating",      type: "text" },
    { key: "overpressure",        label: "Overpressure (%)",     type: "text" },
    { key: "api_orifice",         label: "API Orifice",          type: "text" },
    { key: "relieving_capacity",  label: "Relieving Capacity",   type: "text" },
    { key: "discharge_type",      label: "Discharge Type",       type: "text" },
    { key: "back_pressure_type",  label: "Back Pressure Type",   type: "text" },
    { key: "end_connection",      label: "End Connection",       type: "text" },
    { key: "body_material",       label: "Body Material",        type: "text" },
    { key: "trim_material",       label: "Trim Material",        type: "text" },
    { key: "bonnet_type",         label: "Bonnet Type",          type: "text" },
    { key: "process_fluid",       label: "Process Fluid",        type: "text" },
    { key: "service_fluid",       label: "Service Fluid",        type: "text" },
    { key: "service_phase",       label: "Service Phase",        type: "text" },
    { key: "design_standard",     label: "Design Standard",      type: "text" },
    { key: "certification",       label: "Certification",        type: "text" },
    { key: "operation_type",      label: "Operation Type",       type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  nrv: [
    { key: "valve_type",          label: "Valve Type",         type: "text" },
    { key: "size_nb",             label: "Size (NB)",          type: "text" },
    { key: "pressure_rating",     label: "Pressure Rating",    type: "text" },
    { key: "end_connection",      label: "End Connection",     type: "text" },
    { key: "body_material",       label: "Body Material",      type: "text" },
    { key: "disc_material",       label: "Disc Material",      type: "text" },
    { key: "seat_material",       label: "Seat Material",      type: "text" },
    { key: "ball_material",       label: "Ball Material",      type: "text" },
    { key: "spring",              label: "Spring",             type: "text" },
    { key: "spring_material",     label: "Spring Material",    type: "text" },
    { key: "renewable_seat",      label: "Renewable Seat",     type: "text" },
    { key: "design_standard",     label: "Design Standard",    type: "text" },
    { key: "design_pressure",     label: "Design Pressure (bar)", type: "text" },
    { key: "operating_pressure",  label: "Oper. Pressure (bar)",  type: "text" },
    { key: "process_fluid",       label: "Process Fluid",      type: "text" },
    { key: "area_classification", label: "Area Classification",type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  needle: [
    { key: "valve_type",       label: "Valve Type",         type: "text" },
    { key: "size",             label: "Size",               type: "text" },
    { key: "pressure_rating",  label: "Pressure Rating",    type: "text" },
    { key: "end_connection",   label: "End Connection",     type: "text" },
    { key: "body_material",    label: "Body Material",      type: "text" },
    { key: "stem_material",    label: "Stem Material",      type: "text" },
    { key: "seat_type",        label: "Seat Type",          type: "text" },
    { key: "packing",          label: "Packing",            type: "text" },
    { key: "flow_pattern",     label: "Flow Pattern",       type: "text" },
    { key: "bonnet_type",      label: "Bonnet Type",        type: "text" },
    { key: "vent_type",        label: "Vent Type",          type: "text" },
    { key: "design_standard",  label: "Design Standard",    type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],

  // ── RAW MATERIALS / PIPING ───────────────────────────────────────────────────
  plates: [
    { key: "plate_type",     label: "Plate Type",     type: "select", opts: ["MS","SS 304","SS 316","Chequered","Boiler Quality Plate"] },
    { key: "material_grade", label: "Material Grade", type: "select",
      opts: [
        "IS 2062 E250","IS 2062 E350",
        "SS304","SS304L","SS316","SS316L",
        "SA 516 Gr 60","SA 516 Gr 70","ASTM A36",
        "SA-240 Gr 304","SA-240 Gr 304L","SA-240 Gr 316","SA-240 Gr 316L",
      ],
      cascade: {
        targetKey: "standard",
        map: {
          "IS 2062 E250":   "IS 2062",
          "IS 2062 E350":   "IS 2062",
          "SS304":          "IS 6911",
          "SS304L":         "IS 6911",
          "SS316":          "IS 6911",
          "SS316L":         "IS 6911",
          "SA 516 Gr 60":   "ASME Sec. II Part A",
          "SA 516 Gr 70":   "ASME Sec. II Part A",
          "ASTM A36":       "ASME Sec. II Part A",
          "SA-240 Gr 304":  "ASME Sec. II Part A",
          "SA-240 Gr 304L": "ASME Sec. II Part A",
          "SA-240 Gr 316":  "ASME Sec. II Part A",
          "SA-240 Gr 316L": "ASME Sec. II Part A",
        },
      },
    },
    { key: "thickness_mm",   label: "Thickness (mm)", type: "select", opts: ["3","5","6","8","10","12","16","18","20","25","32","40"] },
    { key: "width_mm",       label: "Width (mm)",     type: "select", opts: ["1000","1250","1500","2000","2500"] },
    { key: "length_mm",      label: "Length (mm)",    type: "select", opts: ["2000","2500","3000","6000"] },
    { key: "standard",       label: "Standard",       type: "select", opts: ["IS 2062","IS 6911","ASME Sec. II Part A"] },
  ],
  pipes: [
    { key: "section_type",   label: "Pipe / Section Type", type: "select", opts: ["Round Pipe","Square Pipe","Rectangular Pipe","Seamless","ERW","GI","MS","SS"] },
    { key: "material_grade", label: "Material Grade",      type: "select", opts: ["ASTM A106 Gr B","ASTM A53","IS 1239","IS 3589","SS 304","SS 316"] },
    { key: "nb_mm",          label: "Nominal Bore (NB)",   type: "select", opts: ["15","20","25","32","40","50","65","80","100","150","200","250","300"] },
    { key: "schedule",       label: "Schedule",            type: "select", opts: ["Sch 10","Sch 20","Sch 40","Sch 80","Sch 160","XS","XXS"] },
    { key: "length",         label: "Length",              type: "select", opts: ["3m","6m","12m","Random"] },
    { key: "standard",       label: "Standard",            type: "select", opts: ["ASTM","ASME","IS","DIN","EN","JIS"] },
  ],
  fittings: [
    { key: "fitting_type", label: "Fitting Type",   type: "select", opts: ["Elbow","Tee","Reducer","Union","Coupling","Cap","Cross","Nipple"] },
    { key: "end_type",     label: "End Type",        type: "select", opts: ["Threaded","Socket Weld","Butt Weld","Flanged"] },
    { key: "size_nb",      label: "Size (NB)",       type: "select", opts: ["15","20","25","32","40","50","65","80","100","150","200"] },
    { key: "rating",       label: "Rating / Class",  type: "select", opts: ["Class 150","Class 300","Class 600","PN10","PN16","PN25","PN40"] },
    { key: "material",     label: "Material",        type: "select", opts: ["MS","CS","SS 304","SS 316","GI","Alloy Steel"] },
    { key: "standard",     label: "Standard",        type: "select", opts: ["ASME B16.9","ASME B16.11","IS","DIN","EN"] },
  ],
  flanges: [
    { key: "flange_type", label: "Flange Type",    type: "select", opts: ["Weld Neck (WN)","Slip-On (SO)","Blind (BL)","Socket Weld (SW)","Threaded (THD)","Lap Joint (LJ)","Orifice"] },
    { key: "size_nb",     label: "Size (NB)",       type: "select", opts: ["15","20","25","32","40","50","65","80","100","150","200","250","300"] },
    { key: "pressure",    label: "Pressure Class",  type: "select", opts: ["Class 150","Class 300","Class 600","Class 900","Class 1500","PN10","PN16","PN25","PN40"] },
    { key: "facing",      label: "Facing",          type: "select", opts: ["RF (Raised Face)","FF (Flat Face)","RTJ (Ring Type Joint)"] },
    { key: "material",    label: "Material",        type: "select", opts: ["CS","ASTM A105","ASTM A182 F304","ASTM A182 F316","Alloy Steel"] },
    { key: "standard",    label: "Standard",        type: "select", opts: ["ASME B16.5","ASME B16.47","IS","DIN","EN"] },
  ],
  fasteners: [
    { key: "fastener_type", label: "Fastener Type",  type: "select", opts: ["Stud Bolt","Hex Bolt","Socket Head Cap Screw","Nut","Washer"] },
    { key: "size_dia",      label: "Size (dia)",     type: "select", opts: ["M8","M10","M12","M16","M20","M24","M30"] },
    { key: "grade",         label: "Grade / Class",  type: "select", opts: ["2H/B7","A2-70","A4-80","8.8","10.9","12.9"] },
    { key: "length",        label: "Length (mm)",    type: "text" },
    { key: "standard",      label: "Standard",       type: "select", opts: ["ASME B18.2","ISO","IS","DIN"] },
  ],
  gaskets: [
    { key: "gasket_type", label: "Gasket Type",    type: "select", opts: ["Spiral Wound","Ring Type Joint (RTJ)","Full Face (FF)","Raised Face (RF)","Sheet Gasket"] },
    { key: "size_nb",     label: "Size (NB)",       type: "select", opts: ["15","20","25","32","40","50","65","80","100","150","200","250","300"] },
    { key: "pressure",    label: "Pressure Class",  type: "select", opts: ["Class 150","Class 300","Class 600","PN10","PN16","PN25","PN40"] },
    { key: "thickness",   label: "Thickness (mm)",  type: "select", opts: ["1.5","2","3","4","5","6"] },
    { key: "material",    label: "Material",        type: "select", opts: ["Spiral Wound SS316+Graphite","PTFE","Graphite","NBR","EPDM","Viton"] },
    { key: "standard",    label: "Standard",        type: "select", opts: ["ASME B16.20","ASME B16.21","IS","DIN"] },
  ],
  structural_steel: [
    { key: "section_type",   label: "Section Type",   type: "text" },
    { key: "size",           label: "Size",           type: "text" },
    { key: "thickness_mm",   label: "Thickness (mm)", type: "text" },
    { key: "material_grade", label: "Material Grade", type: "select", opts: ["IS 2062 E250","IS 2062 E350","ASTM A36"] },
    { key: "length",         label: "Length",         type: "select", opts: ["3m","6m","12m","Random"] },
    { key: "standard",       label: "Standard",       type: "select", opts: ["IS","ASTM","EN","DIN"] },
  ],

  // ── ELECTRICAL / CONTROL ─────────────────────────────────────────────────────
  panel: [
    { key: "panel_type",           label: "Panel Type",              type: "text" },
    { key: "panel_standard",       label: "Panel Standard",          type: "text" },
    { key: "voltage",              label: "Voltage",                 type: "text" },
    { key: "frequency",           label: "Frequency",               type: "text" },
    { key: "bus_rating",           label: "Bus Rating",              type: "text" },
    { key: "short_circuit_rating", label: "Short Circuit Rating",    type: "text" },
    { key: "num_incomer_units",    label: "No. of Incomer Units",    type: "text" },
    { key: "incomer_rating",       label: "Incomer Rating",          type: "text" },
    { key: "num_feeders",          label: "Number of Feeders",       type: "text" },
    { key: "enclosure_type",       label: "Enclosure Type",          type: "text" },
    { key: "enclosure_material",   label: "Enclosure Material",      type: "text" },
    { key: "ip_rating",            label: "IP Rating",               type: "text" },
    { key: "form_of_separation",   label: "Form of Separation",      type: "text" },
    { key: "busbar_material",      label: "Busbar Material",         type: "text" },
    { key: "interlocking",         label: "Interlocking",            type: "text" },
    { key: "anti_condensation",    label: "Anti-condensation Heater",type: "text" },
    { key: "aux_power_supply",     label: "Auxiliary Power Supply",  type: "text" },
    { key: "area_classification",  label: "Area Classification",     type: "text" },
    { key: "explosion_protection", label: "Explosion Protection",    type: "text" },
    { key: "gas_group",            label: "Gas Group",               type: "text" },
    { key: "temperature_class",    label: "Temperature Class",       type: "text" },
    { key: "testing_std",          label: "Testing Standard",        type: "text" },
  ],
  cabling: [
    { key: "cable_type",   label: "Cable Type",          type: "text" },
    { key: "core_config",  label: "Core Configuration",  type: "text" },
    { key: "cable_size",   label: "Conductor Size",      type: "text" },
    { key: "voltage",      label: "Voltage Rating",      type: "text" },
    { key: "insulation",   label: "Insulation",          type: "text" },
    { key: "outer_sheath", label: "Outer Sheath",        type: "text" },
    { key: "armour",       label: "Armour",              type: "text" },
    { key: "screening",    label: "Screening",           type: "text" },
    { key: "laying_type",  label: "Laying Type",         type: "text" },
    { key: "standard",     label: "Standard",            type: "text" },
  ],
  junction_box: [
    { key: "jb_type",             label: "JB Type",                type: "text" },
    { key: "body_material",       label: "Body Material",          type: "text" },
    { key: "mounting",            label: "Mounting",               type: "text" },
    { key: "enclosure_type",      label: "Enclosure (IP Rating)",  type: "text" },
    { key: "num_terminals",       label: "Number of Terminals",    type: "text" },
    { key: "terminal_type",       label: "Terminal Type",          type: "text" },
    { key: "num_cable_entries",   label: "No. of Cable Entries",   type: "text" },
    { key: "num_glands",          label: "Number of Glands",       type: "text" },
    { key: "cable_entry_type",    label: "Cable Entry Type",       type: "text" },
    { key: "cable_gland_type",    label: "Cable Gland Type",       type: "text" },
    { key: "gland_size",          label: "Gland Size",             type: "text" },
    { key: "area_classification", label: "Area Classification",    type: "text" },
    { key: "certification",       label: "Certification",          type: "text" },
    { key: "earthing",            label: "Earthing",               type: "text" },
    { key: "accessories",         label: "Accessories",            type: "text", colSpan: true },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  cooling_tower: [
    { key: "cooling_tower_type", label: "Cooling Tower Type",       type: "text" },
    { key: "construction_type",  label: "Construction Type",        type: "text" },
    { key: "circulation_rate",   label: "Circulation Rate (m³/hr)", type: "text" },
    { key: "heat_load_kcal",     label: "Heat Load (kcal/hr)",      type: "text" },
    { key: "inlet_water_temp",   label: "Inlet Water Temp (°C)",    type: "text" },
    { key: "outlet_water_temp",  label: "Outlet Water Temp (°C)",   type: "text" },
    { key: "wet_bulb_temp",      label: "Wet Bulb Temp (°C)",       type: "text" },
    { key: "fan_type",           label: "Fan Type",                 type: "text" },
    { key: "fan_drive",          label: "Fan Drive",                type: "text" },
    { key: "motor_power_kw",     label: "Motor Power (kW)",         type: "text" },
    { key: "fill_type",          label: "Fill Type",                type: "text" },
    { key: "drift_eliminator",   label: "Drift Eliminator",         type: "text" },
    { key: "louvers",            label: "Louvers",                  type: "text" },
    { key: "casing_material",    label: "Casing Material",          type: "text" },
    { key: "basin_material",     label: "Basin Material",           type: "text" },
    { key: "water_type",         label: "Water Type",               type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  bought_out: [
    { key: "package_type",        label: "Package Type",        type: "text" },
    { key: "capacity",            label: "Capacity",            type: "text" },
    { key: "duty",                label: "Duty",                type: "text" },
    { key: "configuration",       label: "Configuration",       type: "text" },
    { key: "package_components",  label: "Package Components",  type: "text", colSpan: true },
    { key: "fluid",               label: "Process Fluid",       type: "text" },
    { key: "operating_temp",      label: "Operating Temp",      type: "text" },
    { key: "material_class",      label: "Material Class",      type: "text" },
    { key: "area_classification", label: "Area Classification", type: "text" },
    { key: "certification",       label: "Certification",       type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
  components: [
    { key: "component_type",      label: "Component Type",      type: "text" },
    { key: "voltage",             label: "Voltage",             type: "text" },
    { key: "frequency",          label: "Frequency",           type: "text" },
    { key: "current_rating",      label: "Current Rating",      type: "text" },
    { key: "power_kw",            label: "Power (kW)",          type: "text" },
    { key: "coil_voltage",        label: "Coil Voltage",        type: "text" },
    { key: "poles",               label: "Poles",               type: "text" },
    { key: "breaking_capacity",   label: "Breaking Capacity",   type: "text" },
    { key: "ip_rating",           label: "IP Rating",           type: "text" },
    { key: "mounting",            label: "Mounting",            type: "text" },
    { key: "area_classification", label: "Area Classification", type: "text" },
    { key: "explosion_protection",label: "Explosion Protection",type: "text" },
    { key: "certification",       label: "Certification",       type: "text" },
    { key: "design_standard",     label: "Design Standard",     type: "text" },
    { key: "make", label: "Make", type: "text", colSpan: true },
  ],
};

// ── Lookup helper ─────────────────────────────────────────────────────────────
export function getSubgroupFields(subgroupCode: string | null | undefined): SubgroupField[] {
  if (!subgroupCode) return [];
  return SUBGROUP_TA_FIELDS[subgroupCode] ?? [];
}

// ── Build ordered entries for a given attrs object ────────────────────────────
// Returns an array of { label, value } pairs:
//  1. Known fields in registry order (all, even if empty)
//  2. Any extra keys in attrs not in the registry (at the end)
export function buildDatasheetEntries(
  subgroupCode: string | null | undefined,
  attrs: Record<string, unknown> | null | undefined,
  showEmpty = false,
): { label: string; value: string }[] {
  const fields = getSubgroupFields(subgroupCode);
  const safeAttrs = attrs ?? {};
  const knownKeys = new Set(fields.map(f => f.key));
  const result: { label: string; value: string }[] = [];

  for (const f of fields) {
    const raw = safeAttrs[f.key];
    const value = Array.isArray(raw)
      ? (raw as string[]).filter(Boolean).join(", ")
      : (raw === null || raw === undefined ? "" : String(raw));
    if (value || showEmpty) {
      result.push({ label: f.label, value: value || "—" });
    }
  }

  // Extra keys not in registry
  for (const [key, raw] of Object.entries(safeAttrs)) {
    if (knownKeys.has(key)) continue;
    const value = Array.isArray(raw)
      ? (raw as string[]).filter(Boolean).join(", ")
      : (raw === null || raw === undefined ? "" : String(raw));
    if (value || showEmpty) {
      const label = key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
      result.push({ label, value: value || "—" });
    }
  }

  return result;
}
