-- LLM Prompt Engine Database Schema
-- Create tables for automated business intelligence generation

-- Core prompt registry table
CREATE TABLE IF NOT EXISTS llm_prompts_registry (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    template TEXT NOT NULL,
    category VARCHAR(100) NOT NULL, -- 'projects', 'quality', 'finance', 'hr', 'procurement'
    model VARCHAR(50) DEFAULT 'gpt-4o', -- 'gpt-4', 'gpt-4o', 'claude-3-sonnet', 'claude-sonnet-4'
    frequency VARCHAR(20) DEFAULT 'daily', -- 'daily', 'weekly', 'monthly', 'on-demand'
    active BOOLEAN DEFAULT true,
    version INTEGER DEFAULT 1,
    priority INTEGER DEFAULT 5, -- 1-10, higher = more important
    data_query TEXT, -- SQL query or API endpoint to fetch data
    data_parameters JSONB, -- Parameters for the data query
    output_format VARCHAR(50) DEFAULT 'markdown', -- 'markdown', 'json', 'html'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER REFERENCES users(id),
    updated_by INTEGER REFERENCES users(id)
);

-- Prompt execution log
CREATE TABLE IF NOT EXISTS llm_prompt_executions (
    id SERIAL PRIMARY KEY,
    prompt_id INTEGER REFERENCES llm_prompts_registry(id) ON DELETE CASCADE,
    execution_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    model_used VARCHAR(50) NOT NULL,
    data_snapshot JSONB, -- The actual data injected into the prompt
    input_tokens INTEGER,
    output_tokens INTEGER,
    execution_duration_ms INTEGER,
    result TEXT, -- Generated insight/summary
    status VARCHAR(20) DEFAULT 'success', -- 'success', 'failed', 'timeout'
    error_message TEXT,
    cost_usd DECIMAL(10,4), -- Track API costs
    triggered_by VARCHAR(50) DEFAULT 'scheduler' -- 'scheduler', 'manual', 'api'
);

-- User feedback and scoring
CREATE TABLE IF NOT EXISTS llm_prompt_feedback (
    id SERIAL PRIMARY KEY,
    execution_id INTEGER REFERENCES llm_prompt_executions(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5), -- 1-5 stars
    feedback_type VARCHAR(20) NOT NULL, -- 'useful', 'needs_action', 'too_long', 'irrelevant'
    feedback_text TEXT,
    action_taken BOOLEAN DEFAULT false,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Prompt performance metrics
CREATE TABLE IF NOT EXISTS llm_prompt_performance (
    id SERIAL PRIMARY KEY,
    prompt_id INTEGER REFERENCES llm_prompts_registry(id) ON DELETE CASCADE,
    avg_rating DECIMAL(3,2),
    total_executions INTEGER DEFAULT 0,
    total_feedback INTEGER DEFAULT 0,
    success_rate DECIMAL(5,2),
    avg_execution_time_ms INTEGER,
    total_cost_usd DECIMAL(10,4),
    last_executed TIMESTAMP,
    last_tuned TIMESTAMP,
    auto_adjustment_count INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Business insights generated by prompts
CREATE TABLE IF NOT EXISTS llm_business_insights (
    id SERIAL PRIMARY KEY,
    execution_id INTEGER REFERENCES llm_prompt_executions(id) ON DELETE CASCADE,
    category VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    insight_text TEXT NOT NULL,
    priority INTEGER DEFAULT 3, -- 1-5, higher = more urgent
    tags VARCHAR[] DEFAULT '{}',
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP, -- Some insights may be time-sensitive
    viewed_by INTEGER[], -- Track which users have seen this insight
    acknowledged_by INTEGER REFERENCES users(id), -- User who acted on the insight
    acknowledged_at TIMESTAMP,
    archived BOOLEAN DEFAULT false
);

-- Model routing configuration
CREATE TABLE IF NOT EXISTS llm_model_config (
    id SERIAL PRIMARY KEY,
    model_name VARCHAR(50) NOT NULL UNIQUE,
    api_provider VARCHAR(50) NOT NULL, -- 'openai', 'anthropic', 'mistral'
    base_url VARCHAR(255),
    max_tokens INTEGER DEFAULT 4000,
    temperature DECIMAL(3,2) DEFAULT 0.7,
    cost_per_input_token DECIMAL(10,8),
    cost_per_output_token DECIMAL(10,8),
    active BOOLEAN DEFAULT true,
    rate_limit_rpm INTEGER DEFAULT 60, -- requests per minute
    suitable_for VARCHAR[] DEFAULT '{}', -- categories this model is good for
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Scheduler configuration
CREATE TABLE IF NOT EXISTS llm_scheduler_config (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    cron_expression VARCHAR(100) NOT NULL,
    description TEXT,
    active BOOLEAN DEFAULT true,
    last_run TIMESTAMP,
    next_run TIMESTAMP,
    run_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_llm_prompts_category ON llm_prompts_registry(category);
CREATE INDEX IF NOT EXISTS idx_llm_prompts_active ON llm_prompts_registry(active);
CREATE INDEX IF NOT EXISTS idx_llm_executions_prompt_id ON llm_prompt_executions(prompt_id);
CREATE INDEX IF NOT EXISTS idx_llm_executions_time ON llm_prompt_executions(execution_time);
CREATE INDEX IF NOT EXISTS idx_llm_feedback_execution_id ON llm_prompt_feedback(execution_id);
CREATE INDEX IF NOT EXISTS idx_llm_insights_category ON llm_business_insights(category);
CREATE INDEX IF NOT EXISTS idx_llm_insights_generated_at ON llm_business_insights(generated_at);

-- Insert default model configurations
INSERT INTO llm_model_config (model_name, api_provider, max_tokens, temperature, cost_per_input_token, cost_per_output_token, suitable_for) 
VALUES 
    ('gpt-4o', 'openai', 4000, 0.7, 0.000005, 0.000015, ARRAY['analysis', 'summarization', 'recommendations']),
    ('gpt-4', 'openai', 8000, 0.7, 0.00003, 0.00006, ARRAY['complex_analysis', 'detailed_reports']),
    ('claude-sonnet-4', 'anthropic', 4000, 0.7, 0.000003, 0.000015, ARRAY['detailed_analysis', 'strategic_insights']),
    ('claude-3-sonnet', 'anthropic', 4000, 0.7, 0.000003, 0.000015, ARRAY['balanced_analysis', 'reports'])
ON CONFLICT (model_name) DO NOTHING;

-- Insert default scheduler configurations
INSERT INTO llm_scheduler_config (name, cron_expression, description) 
VALUES 
    ('daily_morning_reports', '0 8 * * *', 'Generate daily business intelligence reports at 8 AM'),
    ('weekly_summary', '0 9 * * 1', 'Generate weekly summary reports every Monday at 9 AM'),
    ('monthly_analysis', '0 10 1 * *', 'Generate monthly analysis reports on the 1st at 10 AM')
ON CONFLICT (name) DO NOTHING;