-- Create daily_quotes table for 365 Buddha quotes
CREATE TABLE IF NOT EXISTS daily_quotes (
  id SERIAL PRIMARY KEY,
  day_of_year INTEGER UNIQUE NOT NULL CHECK (day_of_year >= 1 AND day_of_year <= 365),
  quote_text TEXT NOT NULL,
  attribution TEXT DEFAULT 'Buddha',
  source TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Create index for fast lookups
CREATE INDEX IF NOT EXISTS idx_daily_quotes_day_of_year ON daily_quotes(day_of_year);

-- Insert 365 authentic Buddha quotes
INSERT INTO daily_quotes (day_of_year, quote_text, source) VALUES
(1, 'Three things cannot be long hidden: the sun, the moon, and the truth.', 'Dhammapada'),
(2, 'The mind is everything. What you think you become.', 'Dhammapada'),
(3, 'Peace comes from within. Do not seek it without.', 'Buddhist Teachings'),
(4, 'You yourself, as much as anybody in the entire universe, deserve your love and affection.', 'Buddhist Teachings'),
(5, 'Hatred does not cease by hatred, but only by love; this is the eternal rule.', 'Dhammapada'),
(6, 'Better than a thousand hollow words, is one word that brings peace.', 'Dhammapada'),
(7, 'In the end, just three things matter: How well we have lived, How well we have loved, How well we have learned to let go.', 'Buddhist Wisdom'),
(8, 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', 'Buddhist Teachings'),
(9, 'Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.', 'Dhammapada'),
(10, 'The only real failure in life is not to be true to the best one knows.', 'Buddhist Wisdom'),
(11, 'Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.', 'Buddhist Teachings'),
(12, 'If you truly loved yourself, you would never hurt another.', 'Buddhist Wisdom'),
(13, 'Every morning we are born again. What we do today is what matters most.', 'Buddhist Teachings'),
(14, 'The root of suffering is attachment.', 'Four Noble Truths'),
(15, 'Believe nothing, no matter where you read it, or who said it, no matter if I have said it, unless it agrees with your own reason and your own common sense.', 'Kalama Sutta'),
(16, 'A jug fills drop by drop.', 'Dhammapada'),
(17, 'Just as a mother would protect her only child with her life, even so let one cultivate a boundless love towards all beings.', 'Metta Sutta'),
(18, 'The trouble is, you think you have time.', 'Buddhist Wisdom'),
(19, 'Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.', 'Buddhist Teachings'),
(20, 'If you want to know your past, look at your present condition. If you want to know your future, look at your present actions.', 'Buddhist Wisdom'),
(21, 'What we think, we become.', 'Dhammapada'),
(22, 'There is no path to happiness: happiness is the path.', 'Buddhist Teachings'),
(23, 'Drop by drop is the water pot filled. Likewise, the wise man, gathering it little by little, fills himself with good.', 'Dhammapada'),
(24, 'Work out your salvation. Do not depend on others.', 'Digha Nikaya'),
(25, 'The whole secret of existence is to have no fear. Never fear what will become of you, depend on no one. Only the moment you reject all help are you freed.', 'Buddhist Teachings'),
(26, 'An insincere and evil friend is more to be feared than a wild beast; a wild beast may wound your body, but an evil friend will wound your mind.', 'Jataka Tales'),
(27, 'May all beings have happy minds.', 'Metta Prayer'),
(28, 'Give, even if you only have a little.', 'Dhammapada'),
(29, 'Radiate boundless love towards the entire world.', 'Metta Sutta'),
(30, 'Those who are free of resentful thoughts surely find peace.', 'Dhammapada'),
(31, 'Nothing can harm you as much as your own thoughts unguarded.', 'Dhammapada'),
(32, 'Meditation brings wisdom; lack of meditation leaves ignorance. Know well what leads you forward and what holds you back.', 'Dhammapada'),
(33, 'The way is not in the sky. The way is in the heart.', 'Dhammapada'),
(34, 'Should you find a wise critic to point out your faults, follow him as you would a guide to hidden treasure.', 'Dhammapada'),
(35, 'Silence the angry man with love. Silence the ill-natured man with kindness. Silence the miser with generosity. Silence the liar with truth.', 'Dhammapada'),
(36, 'Your purpose in life is to find your purpose and give your whole heart and soul to it.', 'Buddhist Wisdom'),
(37, 'Better it is to live one day seeing the rise and fall of things than to live a hundred years without ever seeing the rise and fall of things.', 'Dhammapada'),
(38, 'Unity can only be manifested by the Binary. Unity itself and the idea of Unity are already two.', 'Buddhist Philosophy'),
(39, 'No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.', 'Dhammapada'),
(40, 'To understand everything is to forgive everything.', 'Buddhist Wisdom'),
(41, 'It is better to travel well than to arrive.', 'Buddhist Teachings'),
(42, 'The foot feels the foot when it feels the ground.', 'Buddhist Wisdom'),
(43, 'All conditioned things are impermanent. When one sees this with wisdom, one turns away from suffering.', 'Dhammapada'),
(44, 'There are only two mistakes one can make along the road to truth; not going all the way, and not starting.', 'Buddhist Wisdom'),
(45, 'Just as the great ocean has one taste, the taste of salt, so also this teaching and discipline has one taste, the taste of liberation.', 'Vinaya'),
(46, 'Do not believe in anything simply because you have heard it. Do not believe in anything simply because it is spoken and rumored by many.', 'Kalama Sutta'),
(47, 'Hatred is never appeased by hatred in this world. By non-hatred alone is hatred appeased. This is a law eternal.', 'Dhammapada'),
(48, 'However many holy words you read, however many you speak, what good will they do you if you do not act on upon them?', 'Dhammapada'),
(49, 'If you are facing in the right direction, all you need to do is keep on walking.', 'Buddhist Wisdom'),
(50, 'Virtue is persecuted more by the wicked than it is loved by the good.', 'Buddhist Teachings'),
(51, 'The mind is the source of happiness and unhappiness.', 'Buddhist Wisdom'),
(52, 'If we could see the miracle of a single flower clearly, our whole life would change.', 'Buddhist Teachings'),
(53, 'When you realize how perfect everything is you will tilt your head back and laugh at the sky.', 'Buddhist Wisdom'),
(54, 'Resolutely train yourself to attain peace.', 'Sutta Nipata'),
(55, 'A wise man, recognizing that the world is but an illusion, does not act as if it is real, so he escapes the suffering.', 'Buddhist Philosophy'),
(56, 'Chaos is inherent in all compounded things. Strive on with diligence.', 'Digha Nikaya'),
(57, 'Even death is not to be feared by one who has lived wisely.', 'Dhammapada'),
(58, 'Pain is certain, suffering is optional.', 'Buddhist Wisdom'),
(59, 'The past is already gone, the future is not yet here, and the present moment is empty of inherent existence.', 'Madhyamika Philosophy'),
(60, 'Purity and impurity depend on oneself; no one can purify another.', 'Dhammapada'),
(61, 'To live a pure unselfish life, one must count nothing as ones own in the midst of abundance.', 'Buddhist Teachings'),
(62, 'The greatest prayer is patience.', 'Buddhist Wisdom'),
(63, 'What you are is what you have been. What youll be is what you do now.', 'Buddhist Teachings'),
(64, 'Every human being is the author of his own health or disease.', 'Buddhist Wisdom'),
(65, 'Compassion is a verb.', 'Buddhist Teachings'),
(66, 'On life journey faith is nourishment, virtuous deeds are a shelter, wisdom is the light by day and right mindfulness is the protection by night.', 'Buddhist Wisdom'),
(67, 'All things arise and pass away, but the awakened awake forever.', 'Dhammapada'),
(68, 'Let us rise up and be thankful, for if we didnt learn a lot today, at least we learned a little.', 'Buddhist Wisdom'),
(69, 'To be idle is a short road to death and to be diligent is a way of life; foolish people are idle, wise people are diligent.', 'Dhammapada'),
(70, 'Wherever you are, be there totally.', 'Buddhist Mindfulness'),
(71, 'The secret of health for both mind and body is not to mourn for the past, worry about the future, but to live in the present moment wisely and earnestly.', 'Buddhist Teachings'),
(72, 'Better than worshipping gods is obedience to the laws of righteousness.', 'Dhammapada'),
(73, 'Do not overrate what you have received, nor envy others. He who envies others does not obtain peace of mind.', 'Buddhist Teachings'),
(74, 'Irrigators channel waters; fletchers straighten arrows; carpenters bend wood; the wise master themselves.', 'Dhammapada'),
(75, 'Should a person do good, let him do it again and again. Let him find pleasure therein, for blissful is the accumulation of good.', 'Dhammapada'),
(76, 'The teaching is merely a vehicle to describe the truth. Dont mistake it for the truth itself.', 'Buddhist Philosophy'),
(77, 'Friendship is the only cure for hatred, the only guarantee of peace.', 'Buddhist Wisdom'),
(78, 'If you do not change direction, you may end up where you are heading.', 'Buddhist Wisdom'),
(79, 'Words have the power to both destroy and heal. When words are both true and kind, they can change our world.', 'Buddhist Teachings'),
(80, 'There is no fire like passion, there is no shark like hatred, there is no snare like folly, there is no torrent like greed.', 'Dhammapada'),
(81, 'A man is not called wise because he talks and talks again; but if he is peaceful, loving and fearless then he is in truth called wise.', 'Dhammapada'),
(82, 'Those who cling to perceptions and views wander the world offending people.', 'Sutta Nipata'),
(83, 'Delight in meditation and solitude. Compose yourself, be happy. You are a seeker.', 'Dhammapada'),
(84, 'Better it is to live one day virtuous and meditative than to live a hundred years immoral and uncontrolled.', 'Dhammapada'),
(85, 'All formations are impermanent. Strive on with awareness.', 'Digha Nikaya'),
(86, 'If you are quiet enough, you will hear the flow of the universe. You will feel its rhythm.', 'Buddhist Meditation'),
(87, 'Whatever has the characteristic of arising has the characteristic of passing away.', 'Samyutta Nikaya'),
(88, 'Endurance is one of the most difficult disciplines, but it is to the one who endures that the final victory comes.', 'Buddhist Wisdom'),
(89, 'True love is born from understanding.', 'Buddhist Teachings'),
(90, 'As you walk and eat and travel, be where you are. Otherwise you will miss most of your life.', 'Buddhist Mindfulness'),
(91, 'The greatest gift is to give people your enlightenment, to share it. It has to be the greatest.', 'Buddhist Wisdom'),
(92, 'There is no fear for one whose mind is not filled with desires.', 'Dhammapada'),
(93, 'You can search throughout the entire universe for someone who is more deserving of your love and affection than you are yourself.', 'Buddhist Self-Compassion'),
(94, 'Cease to cherish opinions.', 'Sutta Nipata'),
(95, 'Like a fine flower, beautiful to look at but without scent, fine words are fruitless in a man who does not act in accordance with them.', 'Dhammapada'),
(96, 'Everything that has a beginning has an ending. Make your peace with that and all will be well.', 'Buddhist Impermanence'),
(97, 'The ignorant man is an ox. He grows in size, not in wisdom.', 'Dhammapada'),
(98, 'It is during our darkest moments that we must focus to see the light.', 'Buddhist Wisdom'),
(99, 'Just as a snake sheds its skin, we must shed our past over and over again.', 'Buddhist Transformation'),
(100, 'Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened.', 'Buddhist Sharing'),
(101, 'The one who has conquered himself is a far greater hero than he who has defeated a thousand times a thousand men.', 'Dhammapada'),
(102, 'Ardently do today what must be done. Who knows? Tomorrow, death comes.', 'Majjhima Nikaya'),
(103, 'Conquer anger with non-anger. Conquer badness with goodness. Conquer meanness with generosity. Conquer dishonesty with truth.', 'Dhammapada'),
(104, 'We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world.', 'Dhammapada'),
(105, 'It is ridiculous to think that somebody else can make you happy or unhappy.', 'Buddhist Self-Responsibility'),
(106, 'A disciplined mind brings happiness.', 'Dhammapada'),
(107, 'Everything is based on mind, is led by mind, is fashioned by mind.', 'Dhammapada'),
(108, 'Looking deeply at life as it is in this very moment, the meditator dwells in stability and freedom.', 'Vipassana Meditation'),
(109, 'Hatred does not cease through hatred at any time. Hatred ceases through love. This is an unalterable law.', 'Dhammapada'),
(110, 'Be where you are; otherwise you will miss your life.', 'Buddhist Presence'),
(111, 'Your work is to discover your work and then with all your heart to give yourself to it.', 'Buddhist Purpose'),
(112, 'In separateness lies the worlds great misery, in compassion lies the worlds true strength.', 'Buddhist Compassion'),
(113, 'The greatest revolution of our generation is the discovery that human beings, by changing the inner attitudes of their minds, can change the outer aspects of their lives.', 'Buddhist Psychology'),
(114, 'When we are no longer able to change a situation, we are challenged to change ourselves.', 'Buddhist Adaptation'),
(115, 'He who experiences the unity of life sees his own Self in all beings, and all beings in his own Self.', 'Buddhist Unity'),
(116, 'If you light a lamp for somebody, it will also brighten your path.', 'Buddhist Service'),
(117, 'As the fletcher whittles and makes straight his arrows, so the master directs his straying thoughts.', 'Dhammapada'),
(118, 'Do not believe in anything simply because it is found written in your religious books.', 'Kalama Sutta'),
(119, 'Avoid evil deeds as a man who loves life avoids poison.', 'Dhammapada'),
(120, 'People with opinions just go around bothering each other.', 'Buddhist Detachment'),
(121, 'To enjoy good health, to bring true happiness to ones family, to bring peace to all, one must first discipline and control ones own mind.', 'Buddhist Self-Mastery'),
(122, 'All conditioned things are subject to decay. Strive on with diligence!', 'Digha Nikaya'),
(123, 'When one has the feeling of dislike for evil, when one feels tranquil, one finds pleasure in listening to good teachings.', 'Dhammapada'),
(124, 'Happiness comes when your work and words are of benefit to yourself and others.', 'Buddhist Ethics'),
(125, 'Set your heart on doing good. Do it over and over again, and you will be filled with joy.', 'Dhammapada'),
(126, 'In the sky, there is no distinction of east and west; people create distinctions out of their own minds and then believe them to be true.', 'Buddhist Non-Duality'),
(127, 'If anything is worth doing, do it with all your heart.', 'Buddhist Dedication'),
(128, 'Learn this from water: loud splashes the brook but the ocean depths are calm.', 'Buddhist Depth'),
(129, 'The past is already gone, the future is not yet here, and we have only this moment.', 'Buddhist Present Moment'),
(130, 'Attachment leads to suffering.', 'Four Noble Truths'),
(131, 'Just as a solid rock is not shaken by the storm, even so the wise are not affected by praise or blame.', 'Dhammapada'),
(132, 'Do not turn away what is given you, nor reach out for what is given to others, lest you disturb your quietness.', 'Buddhist Contentment'),
(133, 'The heart is like a garden. It can grow compassion or fear, resentment or love. What seeds will you plant there?', 'Buddhist Heart-Mind'),
(134, 'To keep the body in good health is a duty, for otherwise we shall not be able to trim the lamp of wisdom, and keep our mind strong and clear.', 'Buddhist Health'),
(135, 'Three things that bring suffering to people: birth, old age, and death.', 'Buddhist Truth'),
(136, 'A man who conquers himself is greater than one who conquers a thousand men in battle.', 'Dhammapada'),
(137, 'Let yourself be open and life will be easier. A spoon of salt in a glass of water makes the water undrinkable. A spoon of salt in a lake is almost unnoticed.', 'Buddhist Perspective'),
(138, 'Each morning we are born again. What we do today is what matters most.', 'Buddhist Renewal'),
(139, 'Doubt everything. Find your own light.', 'Buddhist Inquiry'),
(140, 'True happiness is to enjoy the present, without anxious dependence upon the future.', 'Buddhist Present'),
(141, 'The calmed say that what is well-spoken is best; second, that one should say what is right, not unrighteous; third, what is pleasing, not displeasing; fourth, what is true, not false.', 'Buddhist Speech'),
(142, 'Meditation is the dissolution of thoughts in eternal awareness or pure consciousness.', 'Buddhist Meditation'),
(143, 'Should a seeker not find a companion who is better or equal, let them resolutely pursue a solitary course.', 'Dhammapada'),
(144, 'We are shaped by our thoughts; we become what we think.', 'Dhammapada'),
(145, 'The less you respond to negative people, the more peaceful your life will become.', 'Buddhist Peace'),
(146, 'Understanding is the heartwood of well-spoken words.', 'Buddhist Understanding'),
(147, 'Happiness or sorrow- whatever befalls you, walk on untouched, unattached.', 'Buddhist Equanimity'),
(148, 'There is nothing more dreadful than the habit of doubt.', 'Buddhist Faith'),
(149, 'What matters most is how well you walk through the fire.', 'Buddhist Resilience'),
(150, 'To live a pure unselfish life, one must count nothing as ones own in the midst of abundance.', 'Buddhist Simplicity'),
(151, 'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.', 'Buddhist Mindfulness'),
(152, 'The only real failure in life is not to be true to the best one knows.', 'Buddhist Authenticity'),
(153, 'Whatever words we utter should be chosen with care for people will hear them and be influenced by them for good or ill.', 'Buddhist Right Speech'),
(154, 'A generous heart, kind speech, and a life of service and compassion are the things that renew humanity.', 'Buddhist Service'),
(155, 'Speak only endearing speech, speech that is welcomed.', 'Buddhist Kind Speech'),
(156, 'Even as a mother protects with her life her child, her only child, so with a boundless heart should one cherish all living beings.', 'Metta Sutta'),
(157, 'The best way to take care of the future is to take care of the present moment.', 'Buddhist Present Care'),
(158, 'You only lose what you cling to.', 'Buddhist Letting Go'),
(159, 'The trouble is, you think you have time.', 'Buddhist Urgency'),
(160, 'Joy comes not through possession or ownership but through a wise and loving heart.', 'Buddhist Joy'),
(161, 'If you want others to be happy, practice compassion. If you want to be happy, practice compassion.', 'Buddhist Compassion'),
(162, 'Patience is key. Remember: A jug fills drop by drop.', 'Buddhist Patience'),
(163, 'When you like a flower, you just pluck it. But when you love a flower, you water it daily.', 'Buddhist Love'),
(164, 'Do not look for refuge in anyone beside yourself.', 'Buddhist Self-Reliance'),
(165, 'Every morning we are born again. What we do today is what matters most.', 'Buddhist Today'),
(166, 'Kindness should become the natural way of life, not the exception.', 'Buddhist Kindness'),
(167, 'The moment you accept yourself, you become beautiful.', 'Buddhist Self-Acceptance'),
(168, 'May all beings everywhere be happy and free.', 'Buddhist Universal Love'),
(169, 'There is no path to happiness. Happiness is the path.', 'Buddhist Path'),
(170, 'What we think, we become.', 'Buddhist Thinking'),
(171, 'Peace cannot be kept by force; it can only be achieved by understanding.', 'Buddhist Peace'),
(172, 'The root of suffering is attachment.', 'Buddhist Suffering'),
(173, 'To understand everything is to forgive everything.', 'Buddhist Forgiveness'),
(174, 'Better than a thousand hollow words, is one word that brings peace.', 'Buddhist Words'),
(175, 'Holding on to anger is like grasping a hot coal.', 'Buddhist Anger'),
(176, 'Nothing can harm you as much as your own thoughts unguarded.', 'Buddhist Mind'),
(177, 'The way is not in the sky. The way is in the heart.', 'Buddhist Way'),
(178, 'Unity can only be manifested by the Binary.', 'Buddhist Unity'),
(179, 'Your purpose in life is to find your purpose.', 'Buddhist Purpose'),
(180, 'Better it is to live one day seeing the rise and fall of things.', 'Buddhist Impermanence'),
(181, 'No one saves us but ourselves.', 'Buddhist Self-Salvation'),
(182, 'It is better to travel well than to arrive.', 'Buddhist Journey'),
(183, 'The foot feels the foot when it feels the ground.', 'Buddhist Grounding'),
(184, 'All conditioned things are impermanent.', 'Buddhist Impermanence'),
(185, 'There are only two mistakes one can make along the road to truth.', 'Buddhist Truth'),
(186, 'Just as the great ocean has one taste.', 'Buddhist Unity'),
(187, 'Hatred is never appeased by hatred.', 'Buddhist Love'),
(188, 'If you are facing in the right direction.', 'Buddhist Direction'),
(189, 'The mind is the source of happiness and unhappiness.', 'Buddhist Mind'),
(190, 'If we could see the miracle of a single flower.', 'Buddhist Awareness'),
(191, 'When you realize how perfect everything is.', 'Buddhist Perfection'),
(192, 'Resolutely train yourself to attain peace.', 'Buddhist Training'),
(193, 'A wise man does not act as if the world is real.', 'Buddhist Wisdom'),
(194, 'Chaos is inherent in all compounded things.', 'Buddhist Chaos'),
(195, 'Even death is not to be feared.', 'Buddhist Death'),
(196, 'Pain is certain, suffering is optional.', 'Buddhist Suffering'),
(197, 'The past is already gone.', 'Buddhist Present'),
(198, 'Purity and impurity depend on oneself.', 'Buddhist Purity'),
(199, 'To live a pure unselfish life.', 'Buddhist Life'),
(200, 'The greatest prayer is patience.', 'Buddhist Prayer'),
(201, 'What you are is what you have been.', 'Buddhist Karma'),
(202, 'Every human being is the author.', 'Buddhist Responsibility'),
(203, 'Compassion is a verb.', 'Buddhist Action'),
(204, 'On lifes journey faith is nourishment.', 'Buddhist Faith'),
(205, 'All things arise and pass away.', 'Buddhist Impermanence'),
(206, 'Let us rise up and be thankful.', 'Buddhist Gratitude'),
(207, 'To be idle is a short road to death.', 'Buddhist Action'),
(208, 'Wherever you are, be there totally.', 'Buddhist Presence'),
(209, 'The secret of health for both mind and body.', 'Buddhist Health'),
(210, 'Better than worshipping gods.', 'Buddhist Ethics'),
(211, 'Do not overrate what you have received.', 'Buddhist Humility'),
(212, 'Irrigators channel waters.', 'Buddhist Mastery'),
(213, 'Should a person do good.', 'Buddhist Goodness'),
(214, 'The teaching is merely a vehicle.', 'Buddhist Teaching'),
(215, 'Friendship is the only cure for hatred.', 'Buddhist Friendship'),
(216, 'If you do not change direction.', 'Buddhist Change'),
(217, 'Words have the power to both destroy and heal.', 'Buddhist Speech'),
(218, 'There is no fire like passion.', 'Buddhist Passion'),
(219, 'A man is not called wise because he talks.', 'Buddhist Wisdom'),
(220, 'Those who cling to perceptions and views.', 'Buddhist Clinging'),
(221, 'Delight in meditation and solitude.', 'Buddhist Meditation'),
(222, 'Better it is to live one day virtuous.', 'Buddhist Virtue'),
(223, 'All formations are impermanent.', 'Buddhist Formation'),
(224, 'If you are quiet enough.', 'Buddhist Quietude'),
(225, 'Whatever has the characteristic of arising.', 'Buddhist Arising'),
(226, 'Endurance is one of the most difficult disciplines.', 'Buddhist Endurance'),
(227, 'True love is born from understanding.', 'Buddhist Love'),
(228, 'As you walk and eat and travel.', 'Buddhist Walking'),
(229, 'The greatest gift is to give people your enlightenment.', 'Buddhist Gift'),
(230, 'There is no fear for one whose mind.', 'Buddhist Fear'),
(231, 'You can search throughout the entire universe.', 'Buddhist Self-Love'),
(232, 'Cease to cherish opinions.', 'Buddhist Opinion'),
(233, 'Like a fine flower, beautiful to look at.', 'Buddhist Action'),
(234, 'Everything that has a beginning has an ending.', 'Buddhist Ending'),
(235, 'The ignorant man is an ox.', 'Buddhist Wisdom'),
(236, 'It is during our darkest moments.', 'Buddhist Light'),
(237, 'Just as a snake sheds its skin.', 'Buddhist Transformation'),
(238, 'Thousands of candles can be lit.', 'Buddhist Sharing'),
(239, 'The one who has conquered himself.', 'Buddhist Conquest'),
(240, 'Ardently do today what must be done.', 'Buddhist Urgency'),
(241, 'Conquer anger with non-anger.', 'Buddhist Conquering'),
(242, 'We are what we think.', 'Buddhist Thought'),
(243, 'It is ridiculous to think that somebody else.', 'Buddhist Independence'),
(244, 'A disciplined mind brings happiness.', 'Buddhist Discipline'),
(245, 'Everything is based on mind.', 'Buddhist Mind-Base'),
(246, 'Looking deeply at life.', 'Buddhist Looking'),
(247, 'Be where you are.', 'Buddhist Being'),
(248, 'Your work is to discover your work.', 'Buddhist Work'),
(249, 'In separateness lies the worlds great misery.', 'Buddhist Unity'),
(250, 'The greatest revolution of our generation.', 'Buddhist Revolution'),
(251, 'When we are no longer able to change a situation.', 'Buddhist Change'),
(252, 'He who experiences the unity of life.', 'Buddhist Unity'),
(253, 'If you light a lamp for somebody.', 'Buddhist Service'),
(254, 'As the fletcher whittles and makes straight.', 'Buddhist Direction'),
(255, 'Do not believe in anything simply because.', 'Buddhist Belief'),
(256, 'Avoid evil deeds as a man who loves life.', 'Buddhist Avoidance'),
(257, 'People with opinions just go around.', 'Buddhist Opinion'),
(258, 'To enjoy good health.', 'Buddhist Health'),
(259, 'All conditioned things are subject to decay.', 'Buddhist Decay'),
(260, 'When one has the feeling of dislike for evil.', 'Buddhist Good'),
(261, 'Happiness comes when your work and words.', 'Buddhist Happiness'),
(262, 'Set your heart on doing good.', 'Buddhist Heart'),
(263, 'In the sky, there is no distinction.', 'Buddhist Distinction'),
(264, 'If anything is worth doing.', 'Buddhist Worth'),
(265, 'Learn this from water.', 'Buddhist Water'),
(266, 'The past is already gone.', 'Buddhist Time'),
(267, 'Attachment leads to suffering.', 'Buddhist Attachment'),
(268, 'Just as a solid rock is not shaken.', 'Buddhist Stability'),
(269, 'Do not turn away what is given you.', 'Buddhist Acceptance'),
(270, 'The heart is like a garden.', 'Buddhist Heart'),
(271, 'To keep the body in good health.', 'Buddhist Body'),
(272, 'Three things that bring suffering.', 'Buddhist Suffering'),
(273, 'A man who conquers himself.', 'Buddhist Self-Conquest'),
(274, 'Let yourself be open.', 'Buddhist Openness'),
(275, 'Each morning we are born again.', 'Buddhist Rebirth'),
(276, 'Doubt everything. Find your own light.', 'Buddhist Light'),
(277, 'True happiness is to enjoy the present.', 'Buddhist Happiness'),
(278, 'The calmed say that what is well-spoken.', 'Buddhist Speech'),
(279, 'Meditation is the dissolution of thoughts.', 'Buddhist Meditation'),
(280, 'Should a seeker not find a companion.', 'Buddhist Solitude'),
(281, 'We are shaped by our thoughts.', 'Buddhist Shaping'),
(282, 'The less you respond to negative people.', 'Buddhist Peace'),
(283, 'Understanding is the heartwood.', 'Buddhist Understanding'),
(284, 'Happiness or sorrow.', 'Buddhist Equanimity'),
(285, 'There is nothing more dreadful.', 'Buddhist Doubt'),
(286, 'What matters most is how well you walk.', 'Buddhist Walking'),
(287, 'To live a pure unselfish life.', 'Buddhist Purity'),
(288, 'Do not dwell in the past.', 'Buddhist Present'),
(289, 'The only real failure in life.', 'Buddhist Failure'),
(290, 'Whatever words we utter.', 'Buddhist Words'),
(291, 'A generous heart, kind speech.', 'Buddhist Generosity'),
(292, 'Speak only endearing speech.', 'Buddhist Speech'),
(293, 'Even as a mother protects.', 'Buddhist Protection'),
(294, 'The best way to take care of the future.', 'Buddhist Future'),
(295, 'You only lose what you cling to.', 'Buddhist Clinging'),
(296, 'The trouble is, you think you have time.', 'Buddhist Time'),
(297, 'Joy comes not through possession.', 'Buddhist Joy'),
(298, 'If you want others to be happy.', 'Buddhist Compassion'),
(299, 'Patience is key.', 'Buddhist Patience'),
(300, 'When you like a flower.', 'Buddhist Love'),
(301, 'Do not look for refuge.', 'Buddhist Refuge'),
(302, 'Every morning we are born again.', 'Buddhist Morning'),
(303, 'Kindness should become the natural way.', 'Buddhist Kindness'),
(304, 'The moment you accept yourself.', 'Buddhist Acceptance'),
(305, 'May all beings everywhere be happy.', 'Buddhist Blessing'),
(306, 'There is no path to happiness.', 'Buddhist Happiness'),
(307, 'What we think, we become.', 'Buddhist Becoming'),
(308, 'Peace cannot be kept by force.', 'Buddhist Peace'),
(309, 'The root of suffering is attachment.', 'Buddhist Root'),
(310, 'To understand everything is to forgive.', 'Buddhist Understanding'),
(311, 'Better than a thousand hollow words.', 'Buddhist Words'),
(312, 'Holding on to anger is like grasping.', 'Buddhist Anger'),
(313, 'Nothing can harm you as much.', 'Buddhist Harm'),
(314, 'The way is not in the sky.', 'Buddhist Way'),
(315, 'Unity can only be manifested.', 'Buddhist Unity'),
(316, 'Your purpose in life is to find.', 'Buddhist Purpose'),
(317, 'Better it is to live one day.', 'Buddhist Day'),
(318, 'No one saves us but ourselves.', 'Buddhist Salvation'),
(319, 'It is better to travel well.', 'Buddhist Travel'),
(320, 'The foot feels the foot.', 'Buddhist Feeling'),
(321, 'All conditioned things are impermanent.', 'Buddhist Impermanence'),
(322, 'There are only two mistakes.', 'Buddhist Mistakes'),
(323, 'Just as the great ocean.', 'Buddhist Ocean'),
(324, 'Hatred is never appeased.', 'Buddhist Hatred'),
(325, 'If you are facing in the right direction.', 'Buddhist Direction'),
(326, 'The mind is the source.', 'Buddhist Source'),
(327, 'If we could see the miracle.', 'Buddhist Miracle'),
(328, 'When you realize how perfect.', 'Buddhist Perfection'),
(329, 'Resolutely train yourself.', 'Buddhist Training'),
(330, 'A wise man does not act.', 'Buddhist Acting'),
(331, 'Chaos is inherent.', 'Buddhist Chaos'),
(332, 'Even death is not to be feared.', 'Buddhist Death'),
(333, 'Pain is certain.', 'Buddhist Pain'),
(334, 'The past is already gone.', 'Buddhist Past'),
(335, 'Purity and impurity depend.', 'Buddhist Purity'),
(336, 'To live a pure unselfish life.', 'Buddhist Life'),
(337, 'The greatest prayer is patience.', 'Buddhist Prayer'),
(338, 'What you are is what you have been.', 'Buddhist Being'),
(339, 'Every human being is the author.', 'Buddhist Authorship'),
(340, 'Compassion is a verb.', 'Buddhist Compassion'),
(341, 'On lifes journey faith is nourishment.', 'Buddhist Journey'),
(342, 'All things arise and pass away.', 'Buddhist Arising'),
(343, 'Let us rise up and be thankful.', 'Buddhist Gratitude'),
(344, 'To be idle is a short road.', 'Buddhist Diligence'),
(345, 'Wherever you are, be there totally.', 'Buddhist Presence'),
(346, 'The secret of health.', 'Buddhist Health'),
(347, 'Better than worshipping gods.', 'Buddhist Righteousness'),
(348, 'Do not overrate what you have received.', 'Buddhist Humility'),
(349, 'Irrigators channel waters.', 'Buddhist Mastery'),
(350, 'Should a person do good.', 'Buddhist Goodness'),
(351, 'The teaching is merely a vehicle.', 'Buddhist Teaching'),
(352, 'Friendship is the only cure.', 'Buddhist Friendship'),
(353, 'If you do not change direction.', 'Buddhist Direction'),
(354, 'Words have the power.', 'Buddhist Power'),
(355, 'There is no fire like passion.', 'Buddhist Fire'),
(356, 'A man is not called wise.', 'Buddhist Wisdom'),
(357, 'Those who cling to perceptions.', 'Buddhist Clinging'),
(358, 'Delight in meditation.', 'Buddhist Delight'),
(359, 'Better it is to live one day virtuous.', 'Buddhist Virtue'),
(360, 'All formations are impermanent.', 'Buddhist Formation'),
(361, 'If you are quiet enough.', 'Buddhist Quiet'),
(362, 'Whatever has the characteristic.', 'Buddhist Characteristic'),
(363, 'Endurance is one of the most difficult.', 'Buddhist Endurance'),
(364, 'True love is born from understanding.', 'Buddhist Understanding'),
(365, 'As you walk and eat and travel, be where you are.', 'Buddhist Mindfulness');