export const ECR_PRE_PILOT_PA_ANCHOR_EVIDENCE = {
  recordVersion: '1.1.0',
  reviewedAt: '2026-08-29',
  admission: 'IDENTITY_ADMITTED_THERMODYNAMICS_BLOCKED',
  calibrationStatus: 'CALIBRATION_REQUIRED',
  representativePurpose: 'POLAR_AROMATICS_NMP_PARTITIONING_ONLY',
  sulfurRelationship: 'INDEPENDENT_NOT_A_SULFUR_SURROGATE',
  identity: {
    commonName: "4,4'-Bis(alpha,alpha-dimethylbenzyl)diphenylamine",
    systematicName: '4-(2-phenylpropan-2-yl)-N-[4-(2-phenylpropan-2-yl)phenyl]aniline',
    aliases: [
      "4,4'-Bis(1,1-dimethylbenzyl)diphenylamine",
      'Bis(p-cumylphenyl)amine',
      'Naugard 445',
      'Antioxidant 445',
    ],
    cas: '10081-67-1',
    pubchemCid: 82343,
    formula: 'C30H31N',
    molecularWeightGmol: 405.58,
    canonicalSmiles: 'CC(C)(C1=CC=CC=C1)C2=CC=C(C=C2)NC3=CC=C(C=C3)C(C)(C)C4=CC=CC=C4',
    inchi: 'InChI=1S/C30H31N/c1-29(2,23-11-7-5-8-12-23)25-15-19-27(20-16-25)31-28-21-17-26(18-22-28)30(3,4)24-13-9-6-10-14-24/h5-22,31H,1-4H3',
    inchiKey: 'UJAWGGOCYUPCPS-UHFFFAOYSA-N',
    containsSulfur: false,
  },
  rationale: {
    class: 'Exact alkylated-diphenylamine molecular anchor',
    useBasis: 'Commercially identified antioxidant/stabilizer associated with alkylated-diphenylamine chemistry.',
    limitation: 'One exact antioxidant molecule does not characterize the full physical RRBO polar-aromatics distribution.',
  },
  sources: [
    {
      authority: 'NCBI PubChem',
      role: 'IDENTITY_AND_STRUCTURE',
      url: 'https://pubchem.ncbi.nlm.nih.gov/compound/82343',
      machineReadableUrl: 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/82343/property/IUPACName,MolecularFormula,MolecularWeight,CanonicalSMILES,IsomericSMILES,InChI,InChIKey/JSON',
    },
    {
      authority: 'NCBI PubChem',
      role: 'CAS_AND_SYNONYM_ASSOCIATION',
      url: 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/82343/synonyms/JSON',
    },
    {
      authority: 'US EPA Chemical Data Reporting via PubChem',
      role: 'ANTIOXIDANT_STABILIZER_USE_CLASSIFICATION',
      url: 'https://pubchem.ncbi.nlm.nih.gov/compound/82343',
    },
  ],
  thermodynamicClosure: {
    status: 'BLOCKED',
    primaryBlocker: 'POLAR_AROMATICS_THERMODYNAMIC_CLOSURE_UNAVAILABLE',
    assessment: {
      decision: 'NO_PARAMETER_ADMISSION',
      independentlyCheckableRoute: 'EVIDENCE_INVENTORY_AND_PREDECLARED_GATE_REVIEW',
      evidenceBasis: [
        'EXACT_IDENTITY_AND_STRUCTURE_RECORD',
        'FROZEN_MOLECULAR_PAIR_UNIQUAC_PARAMETER_INVENTORY',
        'PUBLISHED_MODIFIED_UNIFAC_DORTMUND_GROUP_AND_INTERACTION_INVENTORY',
        'VENDORED_COSMO_PROFILE_INVENTORY',
        'DIRECT_LLE_EVIDENCE_REGISTRY',
      ],
      requiredGateResults: {
        exactMolecularRepresentation: 'FAIL',
        completeDirectedInteractions: 'FAIL',
        matchingTwoPhaseEquilibriumEvidence: 'FAIL',
        stage1TemperatureCoverage: 'FAIL',
        independentHoldoutReproduction: 'NOT_TESTABLE',
        phaseTopologyReproduction: 'NOT_TESTABLE',
      },
      conclusion:
        'No candidate can be evaluated as an exact PA/NMP/heavy-hydrocarbon equilibrium model without an undocumented substitution or missing parameter.',
    },
    missing: [
      'EXACT_ALKYLATED_DIPHENYLAMINE_SIGMA_PROFILE',
      'COMPLETE_PA_GROUP_DECOMPOSITION_AND_DIRECTED_INTERACTION_SET',
      'DIRECT_MATCHING_PA_NMP_HEAVY_HYDROCARBON_LLE',
    ],
    routesReviewed: {
      frozenMolecularPairUniquac: 'BLOCKED_NO_PA_DIRECTED_PAIR_PARAMETERS',
      modifiedUnifacDortmund: 'BLOCKED_NO_REVIEWED_AROMATIC_SECONDARY_AMINE_GROUP_AND_PAIR_CLOSURE',
      cosmoSac2010: 'BLOCKED_EXACT_PROFILE_ABSENT_AND_CANDIDATE_REJECTED_ON_PHASE_TOPOLOGY',
      openCosmoRs: 'BLOCKED_EXACT_PROFILE_ABSENT_AND_CANDIDATE_REJECTED_ON_PHASE_TOPOLOGY',
    },
    prohibitedSubstitutions: [
      'UNSUBSTITUTED_DIPHENYLAMINE_PROFILE',
      'DI_OR_POLY_INTERACTION_BORROWING',
      'ZERO_FILLED_INTERACTIONS',
      'SULFUR_BEARING_REPRESENTATIVE',
    ],
  },
  applicability: {
    requestedTemperatureC: { minimum: 25, maximum: 100 },
    admittedTemperatureC: null,
    composition: null,
    solventOilMassRatio: null,
    pressure: null,
    phaseRegion: null,
    reason: 'No PA thermodynamic calculation is admitted, so no operating domain is claimed.',
  },
  outputPolicy: {
    predictiveNtWithPositivePaFeed: 'NOT_CALCULABLE',
    fullBasisRrboRecoveryWithPositivePaFeed: 'NOT_CALCULABLE',
    sulfurRemoval: 'NOT_CALCULABLE',
    fiveComponentZeroPaDiagnostic: 'UNCHANGED',
    releaseEligible: false,
  },
} as const;
