#!/usr/bin/env python3
"""Create an allowlisted handover; reads source only, writes under exports only."""
import hashlib
import json
import re
import shutil
import subprocess
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "exports/thermopac-stage2-handover"
RUNTIME = "dist/predictive-nt-runtime-7c-1-6"
digest = lambda b: hashlib.sha256(b).hexdigest()
origins = {}

def add(source, destination):
    src, dst = ROOT / source, OUT / destination
    assert src.is_file() and not src.is_symlink(), source
    assert ".." not in Path(destination).parts
    data = src.read_bytes()
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    assert digest(dst.read_bytes()) == digest(data), destination
    origins[destination] = source

def derived(name, value, source):
    p = OUT / name
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n")
    origins[name] = source

# Verify the complete original runtime before making any export copy.
manifest_path = ROOT / RUNTIME / "predictive-nt-runtime-manifest.json"
assert digest(manifest_path.read_bytes()) == "2482213baab825170ffd9af67b66319674095f5864a9ceccb897b25a5b72e017"
manifest = json.loads(manifest_path.read_text())
for row in manifest["files"]:
    data = (ROOT / RUNTIME / row["path"]).read_bytes()
    assert len(data) == row["bytes"] and digest(data) == row["sha256"], row["path"]
expected = {r["path"] for r in manifest["files"]} | {"predictive-nt-runtime-manifest.json"}
actual = {p.relative_to(ROOT / RUNTIME).as_posix() for p in (ROOT / RUNTIME).rglob("*") if p.is_file()}
assert expected == actual, "Runtime has unmanifested or missing files"
assert not list((ROOT / RUNTIME).rglob("UD")), "Restricted UD directory found"
assert not list((ROOT / RUNTIME).rglob("VT2005")), "Restricted VT directory found"
for rel in sorted(actual):
    add(f"{RUNTIME}/{rel}", f"{RUNTIME}/{rel}")

# Selected integration implementations and recursively resolved local static imports.
seeds = [
    "server/ecr-pre-pilot/predictive-nt-job-service.ts",
    "client/src/lib/predictive-nt-stage-display.ts",
]
boundary = {"server/db.ts", "shared/schema.ts", "server/auth-middleware.ts", "server/storage.ts"}
seen, omitted, missing = set(), [], []
pattern = re.compile(r"""(?:from\s*|import\s*\(|require\s*\()\s*['"](\.[^'"]+)['"]""")
def visit(rel):
    if rel in seen:
        return
    seen.add(rel)
    add(rel, "integration-source/" + rel)
    if not rel.endswith((".ts", ".tsx", ".js", ".mjs")):
        return
    for imp in pattern.findall((ROOT / rel).read_text()):
        base = (ROOT / rel).parent / imp
        options = [base, *[Path(str(base) + ext) for ext in (".ts", ".tsx", ".js", ".json")],
                   base / "index.ts", base / "index.tsx"]
        target = next((p.resolve() for p in options if p.is_file()), None)
        if target is None:
            missing.append({"importer": rel, "import": imp})
            continue
        dest = target.relative_to(ROOT).as_posix()
        if dest in boundary:
            omitted.append({"importer": rel, "import": imp, "destinationAdapterRequired": dest})
        else:
            visit(dest)
for seed in seeds:
    visit(seed)
assert not missing, f"Unresolved selected local static imports: {missing}"
add("server/ecr-pre-pilot/routes.ts", "integration-source/server/ecr-pre-pilot/routes.ts")
add("migrations/ecr_pre_pilot_predictive_nt_jobs.sql", "integration-source/migrations/ecr_pre_pilot_predictive_nt_jobs.sql")
derived("SOURCE-DEPENDENCIES.json", {
    "staticClosureRoots": seeds, "includedClosureFiles": sorted(seen),
    "destinationInfrastructureAdapters": omitted,
    "referenceOnlyFiles": ["server/ecr-pre-pilot/routes.ts"],
    "note": "API router is reference-only, not dependency-closed. Filesystem scientific dependencies are in the full runtime. No server bootstrap/database pool/authentication implementation supplied."
}, "Generated by static local-import tracing; not application execution")

for rel in [
    "package.json", "package-lock.json", "replit.nix",
    "scripts/package-predictive-nt-runtime.mjs",
    "scripts/prepare-production-runtime.mjs",
    "scripts/production-python312-wrapper.sh",
    "scripts/validate-production-nix-offline.py",
    "scripts/validate-predictive-nt-release.mjs",
    "vitest.predictive-nt-release.config.ts",
    "docs/predictive-nt-test-lanes.md",
]:
    add(rel, "build-reference/" + rel)
for name in ["COSMO.hpp", "pybind11_interface.cxx", "LICENSE", "BOUNDARY-PROOF.md"]:
    rel = "research/sources/job-b/boundary-native/" + name
    add(rel, "native-source/" + rel)
for rel in [
    "server/research/ecr-pre-pilot-six-component-thermodynamics/license-evidence.json",
    "server/research/ecr-pre-pilot-six-component-thermodynamics/provenance-manifest.json",
    "server/research/ecr-pre-pilot-cosmosac/provenance-manifest.json",
]:
    add(rel, "licenses-and-provenance/" + rel)
for rel in [
    "tests/ecr-pre-pilot-nt-job.test.ts",
    "tests/predictive-nt-seven-component-v1-6-worker.test.py",
    "tests/predictive-nt-current-engine-gate.test.ts",
    "tests/predictive-nt-progress.test.ts",
    "tests/predictive-nt-stage-display.test.ts",
    "tests/predictive-nt-production-evidence-paths.test.ts",
    "tests/runtime-retirement-acceptance.test.ts",
    "tests/predictive-nt-report-evidence.test.ts",
    "tests/predictive-nt-report-filename.test.ts",
    "tests/ecr-pre-pilot-predictive-nt-report.test.ts",
    "tests/fixtures/predictive_nt_ack_v3_protocol_worker.py",
    "tests/helpers/predictive-nt-test-database.ts",
]:
    add(rel, "verification-source/" + rel)

ref = "deliverables/stage2-report-corrected/"
job = json.loads((ROOT / ref / "frozen-job.json").read_text())
verification = json.loads((ROOT / ref / "verification.json").read_text())
pdf = "Project-236-Stage2-corrected.pdf"
assert digest((ROOT / ref / pdf).read_bytes()) == verification["pdfSha256"]
assert job["status"] == "completed" and job["completed_trials"] == 10
trials = job["result_snapshot"]["trials"]
assert [t["stageCount"] for t in trials] == list(range(1, 11))
assert sum(len(t["stages"]) for t in trials) == 55
assert job["result_snapshot"]["predictiveNt"] == 4
assert job["result_snapshot"]["releaseEligible"] is False
assert job["engine_hash"] == job["result_snapshot"]["engine"]["engineHash"]
for name in ["frozen-job.json", "verification.json", pdf]:
    add(ref + name, "reference/" + name)
derived("reference/stage1-snapshot.json", job["input_snapshot"]["stage1Authority"]["source"], ref + "frozen-job.json#/input_snapshot/stage1Authority/source")
derived("reference/expected-result.json", job["result_snapshot"], ref + "frozen-job.json#/result_snapshot")
request = dict(job["input_snapshot"])
request.update(engineHash=job["engine_hash"], _checkpointProtocol="ACK_V3_ENGINE_CONTRACT")
derived("reference/worker-request.json", request, "Derived from frozen input_snapshot plus recorded engine_hash; no resume")

# Verify original object hashes using the original Node JSON.stringify semantics.
js = """
const fs=require('fs'),c=require('crypto');
const j=JSON.parse(fs.readFileSync(process.argv[1])),v=JSON.parse(fs.readFileSync(process.argv[2]));
const hash=x=>c.createHash('sha256').update(JSON.stringify(x)).digest('hex');
if(hash(j.input_snapshot)!==v.before.input || hash(j.result_snapshot)!==v.before.result) process.exit(1);
console.log('Reference input/result JSON.stringify hashes match archived verification.');
"""
subprocess.run(["node", "-e", js, str(ROOT/ref/"frozen-job.json"), str(ROOT/ref/"verification.json")], check=True)

# Fail on secret-bearing filenames or high-confidence credential content.
# References to env var names and licence-author contacts are not credentials.
blocked_names = {".env", ".npmrc", ".netrc", "id_rsa", "id_ed25519", "credentials.json"}
secret_patterns = [
    rb"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----",
    rb"(?:postgres(?:ql)?|mysql)://[^\\s/:]+:[^\\s/@]+@",
    rb"sk-ant-api[0-9]+-[A-Za-z0-9_-]{30,}",
    rb"AKIA[0-9A-Z]{16}",
]
for p in OUT.rglob("*"):
    if not p.is_file():
        continue
    assert p.name not in blocked_names and not p.name.startswith(".env."), f"Disallowed file: {p.name}"
    if p.suffix.lower() in {".json", ".ts", ".tsx", ".py", ".js", ".mjs", ".md", ".txt", ".sql", ".sh", ".nix"}:
        data = p.read_bytes()
        assert not any(re.search(pattern, data) for pattern in secret_patterns), f"Credential pattern in {p.relative_to(OUT)}"

rows = []
for p in sorted(OUT.rglob("*")):
    if not p.is_file() or p.name in {"INVENTORY.json", "SHA256SUMS"}:
        continue
    name = p.relative_to(OUT).as_posix()
    rows.append({"path": name, "bytes": p.stat().st_size, "sha256": digest(p.read_bytes()),
                 "origin": origins.get(name, "New handover documentation/verification tool")})
derived("INVENTORY.json", {"schema": "THERMOPAC_STAGE2_EXPORT_V1", "files": rows,
    "runtimePayloadCount": manifest["fileCount"], "referenceRerunPerformed": False,
    "sourceDatabaseAccessed": False, "credentialScan": "Allowlisted paths plus high-confidence text patterns; not a general security certification"},
    "Export inventory")
checks = [(r["path"], r["sha256"]) for r in rows]
checks.append(("INVENTORY.json", digest((OUT/"INVENTORY.json").read_bytes())))
(OUT/"SHA256SUMS").write_text("".join(f"{sha}  {name}\n" for name, sha in checks))
subprocess.run(["python3", str(OUT/"verify-export.py")], check=True)
archive = ROOT/"exports/Thermopac-Stage2-Handover-2026-09-25.zip"
with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as z:
    for p in sorted(OUT.rglob("*")):
        if p.is_file():
            z.write(p, p.relative_to(OUT).as_posix())
with zipfile.ZipFile(archive) as z:
    assert z.testzip() is None, "ZIP CRC failure"
    for r in rows:
        assert digest(z.read(r["path"])) == r["sha256"], r["path"]
summary = {"archive": archive.relative_to(ROOT).as_posix(), "bytes": archive.stat().st_size,
           "sha256": digest(archive.read_bytes()), "payloadFiles": len(rows)+2,
           "runtimePayloadFiles": manifest["fileCount"], "localStaticClosureFiles": len(seen),
           "originalRuntimeVerified": True, "zipMembersVerified": True,
           "referenceInputResultAndPdfVerified": True, "scientificRerunPerformed": False}
(ROOT/"exports/Thermopac-Stage2-Handover-2026-09-25.verification.json").write_text(json.dumps(summary, indent=2)+"\n")
print(json.dumps(summary, indent=2))